import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";
import github from './icons/github-mark.svg';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NBA Where'd They Go",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased mt-5 bg-blue-50 h-screen items-center`}
      >
        <div>
          <div className="flex flex-row justify-end">
            <a className="rounded-md bg-blue-500 px-4 py-2 text-white" href="/login">Login</a>
          </div>
          <div className="flex flex-row justify-center">
            <div className="flex flex-col items-center">
              <a href="/">
                <h1 className="text-3xl font-bold underline p-10">Where'd They Go?</h1>
              </a>
              <div className="rounded-3xl bg-blue-400 p-10 w-auto items-center">{children}</div>
            </div>
          </div>
        </div>
        <footer className="flex flex-row items-end justify-center w-full h-full mt-10 rounded-t-xl">
          <div className="flex flex-col items-center justify-center w-full max-h-24">
            <a target="_blank" rel="noopener noreferrer" href="https://github.com/plenahan/nbawheredtheygo"><Image priority className="w-10 pb-4" src={github} alt={""}/></a>
            <p>All Data & Images from <a className="text-blue-500" href="https://www.basketball-reference.com/">Basketball Reference</a></p>
          </div>
        </footer>
      </body>
    </html>
  );
}
