import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NBA Where'd They Go",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-80 my-5 bg-yellow-50 h-screen`}
      >
        <div>
          <div className="flex flex-row justify-end">
            <a className="rounded-md bg-blue-500 px-4 py-2 text-white" href="/login">Login</a>
          </div>
          <div className="flex flex-row justify-center">
            <div className="flex flex-col items-center">
              <a href="/">
                <h1 className="text-3xl font-bold underline p-10">Where'd They Go?</h1>
              </a>
              <div className="rounded-3xl bg-blue-200 p-10 w-auto items-center">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
